services:
  - type: web
    name: laddle-server
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        generateValue: false
        # Set this to your Firebase hosting URL after frontend deployment
